[package]
name = "geph5-broker"
version = "0.1.0"
edition = "2021"
license="MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
argh = "0.1.12"
axum = {version="0.7.4", features=["json"]}
futures-util = "0.3.30"
once_cell = {version="1.19.0", features=["parking_lot"]}
pollster = "0.3.0"
serde = "1.0.197"
serde_json = "1.0.114"
serde_yaml = "0.9.32"
smolscale = "0.4.4"
sqlx = { version = "0.7", features = [ "runtime-tokio-rustls", "postgres", "chrono" ] }
geph5-broker-protocol={path="../../libraries/geph5-broker-protocol"}
geph5-misc-rpc={path="../../libraries/geph5-misc-rpc"}
async-trait = "0.1.77"
nanorpc = "0.1.12"
thiserror = "1.0.57"
tracing = "0.1.40"
rand = "0.8.5"
async-io = "2.3.1"
moka = {version="0.12.5", features=["future"]}
blake3 = "1.5.0"
isocountry = "0.3.2"
ed25519-dalek = "2.1.1"
tokio = { version = "1.0", features = ["full"] }
tracing-subscriber = {version="0.3.18", features=["fmt", "env-filter"]}
nanorpc-sillad={path="../../libraries/nanorpc-sillad"}
sillad={path="../../libraries/sillad"}
mizaru2={path="../../libraries/mizaru2"}
sillad-sosistab3={path="../../libraries/sillad-sosistab3"}
smol-timeout = "0.6.0"
stdcode = "0.1.14"
bytes = {version="1.5.0", features=["serde"]}
argon2 = "0.5.3"
rusty_pool = "0.7.0"
oneshot = "0.1.6"
