[package]
name = "geph5-bridge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geph5-misc-rpc={path="../../libraries/geph5-misc-rpc"}
picomux={path="../../libraries/picomux"}
rand = "0.8.5"
sillad={path="../../libraries/sillad"}
sillad-sosistab3={path="../../libraries/sillad-sosistab3"}
smolscale = "0.4.4"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
geph5-broker-protocol={path="../../libraries/geph5-broker-protocol"}
nanorpc = "0.1.12"
nanorpc-sillad={path="../../libraries/nanorpc-sillad"}
async-trait = "0.1.77"
blake3 = "1.5.0"
async-io = "2.3.1"
tap = "1.0.1"
reqwest = {version="0.11.24", default-features=false, features=["rustls-tls"]}
moka = {version="0.12.5", features=["future"]}
anyhow = "1.0.80"
stdcode = "0.1.14"
smol = "2.0.0"
futures-util = {version="0.3.30", features=["io"]}
deadpool = "0.10.0"
once_cell = "1.19.0"
dashmap = "5.5.3"
