[package]
name = "sillad-sosistab3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayref = "0.3.7"
blake3 = "1.5.0"
chacha20poly1305 = "0.10.1"
rand = "0.8.5"
x25519-dalek = {version="2.0.1", features=["serde"]}
