[package]
name = "picomux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.8"
anyhow = "1.0.79"
async-dup = "1.2.4"
async-event = "0.1.0"
async-task = "4.7.0"
async_io_stream = "0.3.3"
bipe = "0.2.2"
bytemuck = {version="1.14.3", features=["derive", "min_const_generics"]}
bytes = "1.5.0"
dashmap = "5.5.3"
futures-lite = "2.2.0"
futures-util = {version="0.3.30", features=["io"]}
oneshot = "0.1.6"
parking_lot = "0.12.1"
rand = "0.8.5"
recycle-box = "0.2.0"
scopeguard = "1.2.0"
smol-timeout = "0.6.0"
smolscale = "0.4.4"
tachyonix = "0.2.1"
tracing = "0.1.40"
tracing-test = "0.2.4"
async-rw-adapter={path="../async-rw-adapter"}

[dev-dependencies]
argh = "0.1"
smol="2"
socksv5="0.3"
