[package]
name = "geph5-broker-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
async-trait = "0.1.80"
nanorpc = "0.1.12"
serde_json = "1.0.116"
thiserror = "1.0.59"
serde = {version="1.0.200", features=["derive"]}
bytes = {version="1.6.0", features=["serde"]}
ed25519-dalek = {version="2.1.1", features=["serde"]}
stdcode = "0.1.14"
blake3 = {version="1.5.1", features=["serde"]}
isocountry = "0.3.2"
language-tags = {version="0.3.2", features=["serde"]}
serde_with = {version="3.8.1", features=["hex"]}
mizaru2={path="../mizaru2"}
tracing = "0.1.40"
