[package]
name = "sillad"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/geph-official/geph5"
license="ISC"
description="A framework for talking about TCP-like dialers and listeners, within the futures-io ecosystem"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-io = "2.3.1"
async-trait = "0.1.77"
futures-lite = "2.2.0"
futures-util = {version="0.3.30", features=["io"]}
libc = "0.2.153"
pin-project = "1.1.4"
smol-timeout = "0.6.0"
