[package]
name = "sillad"
edition = "2024"
description = "A framework for talking about TCP-like dialers and listeners, within the futures-io ecosystem"
version = "0.2.6"
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.98"
async-io = "2.5.0"
async-trait = "0.1.88"
futures-concurrency = "7.6.3"
futures-lite = "2.6.0"
futures-util = { version = "0.3.31", features = ["io"] }
libc = "0.2.174"
pin-project = "1.1.10"
rand = "0.8.5"
smol-timeout2 = "0.6.1"
tracing = "0.1.41"
