[package]
name = "nano-influxdb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.12.5", default-features = false}
serde = { version = "1.0", features = ["derive"] }